import { VEHICLE } from './constants'
import type { ScenarioConfig, ScenarioId } from './types'

export const SCENARIOS: Record<ScenarioId, ScenarioConfig> = {
  asds: {
    id: 'asds',
    name: 'Drone Ship Recovery',
    shortName: 'ASDS',
    difficulty: 'Guided',
    description: 'Brake the overshooting downrange arc while the ship chases your estimated coast impact, then settle onto its 90 m deck.',
    objective: 'The ship can reposition, but its speed and acceleration are limited. Shape the trajectory so it can keep up.',
    initialAltitude: 70_000,
    initialDownrange: 100_000,
    initialHorizontalVelocity: 1_500,
    initialVerticalVelocity: 500,
    initialMainPropellant: 65_000,
    targetDownrange: 370_000,
    targetWidth: 90,
    targetKind: 'ship',
    targetMotion: {
      maxSpeed: 10,
      maxAcceleration: 0.25,
      responseTime: 18,
      predictionInterval: 0.5,
    },
    vehicle: VEHICLE,
    calibrationNote: 'The initial coast estimate overshoots the ship; drag, retroburn, and limited ship repositioning close the gap.',
  },
  rtls: {
    id: 'rtls',
    name: 'Return to Launch Site',
    shortName: 'RTLS',
    difficulty: 'Expert',
    description: 'Flip with finite RCS, cancel downrange velocity, and fly the booster back to the pad.',
    objective: 'The launch site is behind you. Every second of boost-back costs landing reserve.',
    initialAltitude: 70_000,
    initialDownrange: 20_000,
    initialHorizontalVelocity: 1_550,
    initialVerticalVelocity: 500,
    initialMainPropellant: 165_000,
    targetDownrange: 0,
    targetWidth: 80,
    targetKind: 'pad',
    vehicle: VEHICLE,
    calibrationNote: 'Gameplay-tuned as the higher-Mach, higher-dynamic-pressure mission.',
  },
}
